version: '3.8'
services:
  app:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://doadmin:AVNS_3b1YnGoB1Y5mAysdpOx@postgres:5432/defaultdb
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - UPLOAD_PREFIX=/uploads
      - NOWPAYMENTS_API_KEY=${NOWPAYMENTS_API_KEY}
      - BODY_SIZE_LIMIT=10485760
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - minio


  haproxy:
    build:
      context: haproxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - minio
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD=AVNS_3b1YnGoB1Y5mAysdpOx
      - POSTGRES_DB=defaultdb
    ports:
      - 5433:5432
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":45051"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    expose:
      - 9000
    ports:
      - 45051:45051
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

volumes:
  postgres_data:
  minio_data:
  minio_config:
